import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkLoaded, ClerkLoading, ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes';
import "./globals.css";
import Navbar from "@/components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: [dark],
      variables: { colorPrimary: 'red' },
      signIn: {
        baseTheme: [shadesOfPurple],
        variables: { colorPrimary: 'blue' }
      }
    }}>
      <html lang='en'>
        <body>
          <ClerkLoading>
            <div className="flex justify-center items-center h-screen text-2xl">
              Loading...
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <div className="">
              <Navbar />
            </div>
            <div className="m-20 ">
              {children}
            </div>

          </ClerkLoaded>


        </body>
      </html>
    </ClerkProvider>
  );
}
